### ISSUE TITLE
TypeError occurs if consumer does not implement process()

### ISSUE THREAD

**Issue by dave-shawley** [gmr/rejected#16]
It is possible to get into the generic `except Exception` case of `consumer.Consumer.execute` with a future that does not have an exception set.  The code in question is https://github.com/gmr/rejected/blob/master/rejected/consumer.py#L888-L896

```python
        except Exception as error:
            exc_info = sys.exc_info()
            if concurrent.is_future(result):
                error = result.exception()
                exc_info = result.exc_info()
            self.log_exception('Exception processing delivery %s: %s',
                               message_in.delivery_tag, error,
                               exc_info=exc_info)
            self._measurement.set_tag('exception', error.__class__.__name__)
            raise gen.Return(data.UNHANDLED_EXCEPTION)
```

If the consumer class does not implement the `process` method, then a `NotImplementedError` is raised (that is what `error` is set to) but the `result` is a `Future` that is finished with both the result and exception set to `None`.  Since it is a future, both `error` and `exc_info` are overwritten with `None`.  `log_exception` then tries to iterate over `None` with results in a `TypeError`.  Here is an example traceback:

```
Traceback (most recent call last):
  File "/Users/daveshawley/opt/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/testing.py", line 136, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/testing.py", line 529, in post_coroutine
    timeout=timeout)
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/daveshawley/Source/python/some-consumer/tests/consumer_tests.py", line 74, in test_that_things_work
    'id': '1234-someone@example.org'})
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/rejected/testing.py", line 182, in process_message
    measurement)
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/rejected/consumer.py", line 894, in execute
    exc_info=exc_info)
  File "/Users/daveshawley/Source/python/some-consumer/env/lib/python2.7/site-packages/rejected/consumer.py", line 922, in log_exception
    if all(exc_info):
TypeError: 'NoneType' object is not iterable
```

**Comment by gmr** [comment]
I believe this is now addressed. Closing, let me know if you run into it again.
