### ISSUE TITLE
Consumers fail to reconnect to RabbitMQ (rejected 3.19.5)

### ISSUE THREAD

**Issue by code-fabriek** [gmr/rejected#23]
I came across the following error when running `rejected==3.19.5` and `pika==0.11.2`:
```
[2017-12-12 10:50:34,011 ERROR    21981  pika.callback] Calling <bound method Connection.on_channel_closed of <rejected.process.Connection object at 0x3aa7d50>> for "1:_on_channel_close" failed
Traceback (most recent call last):
  File "/home/usrisg/python_envs/dsm-reporter/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/home/usrisg/python_envs/dsm-reporter/lib/python2.7/site-packages/rejected/process.py", line 166, in on_channel_closed
    self.handle.channel(self.on_channel_open)
  File "/home/usrisg/python_envs/dsm-reporter/lib/python2.7/site-packages/pika/connection.py", line 1153, in channel
    'Channel allocation requires an open connection: %s' % self)
ConnectionClosed: Channel allocation requires an open connection: <TornadoConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
```

This happens when the `process()` method of the consumer takes longer to run than the RabbitMQ heartbeat interval/timeout and the RabbitMQ server closes the connection to the consumer.  In my specific case, a consumer makes a HTTP request that occasionally takes a long time to receive a response(4+ minutes).  The consumer only notices the connection was reset/dropped once the `process()` method finishes.  This then triggers the `on_channel_close()` callback which generates the exception above.  The consumer gets stuck in an undefined state - the consumer process continues to run but never attempts to re-connect to RabbitMQ.

**To reproduce:**
1. Set the heartbeat_interval setting to 30 seconds in `consumer.yaml`
2. Implement a test consumer with a few `time.sleep(60)` calls in the `process()` method
3. Publish a test message on the queue for the test consumer

Here is a log snippet preceding the exception above (after the `process()` method finishes): 
```
[2017-12-12 10:50:29,625 DEBUG    21981  pika.heartbeat] Sending heartbeat frame
[2017-12-12 10:50:29,625 ERROR    21981  pika.adapters.base_connection] Socket Error: 104
[2017-12-12 10:50:29,625 INFO     21981  pika.connection] Disconnected from RabbitMQ at localhost:5672 (-1): error(104, 'Connection reset by peer')
[2017-12-12 10:50:29,626 DEBUG    21981  pika.heartbeat] Removing timeout for next heartbeat interval
[2017-12-12 10:50:29,626 WARNING  21981  pika.adapters.base_connection] Connection is closed but not stopping IOLoop
[2017-12-12 10:50:29,626 DEBUG    21981  pika.channel] Handling meta-close on <Channel number=1 OPEN conn=<TornadoConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
[2017-12-12 10:50:29,627 DEBUG    21981  pika.callback] Processing 1:_on_channel_close
[2017-12-12 10:50:29,627 DEBUG    21981  pika.callback] Calling <bound method Connection.on_channel_closed of <rejected.process.Connection object at 0x3aa7d50>> for "1:_on_channel_close"
[2017-12-12 10:50:32,821 DEBUG    21981  rejected.process] Connection dsm-rabbitmq channel was closed: (-1) error(104, 'Connection reset by peer')
[2017-12-12 10:50:32,821 DEBUG    21981  rejected.state] State changing from Processing to Connecting
```

I was able to fix this with some minor changes applied against the 3.19.5 tag:
https://github.com/code-fabriek/rejected/commit/d21c95a0735831994a5c56a8d7643233e6202a32

It looks like there are some changes on master for the 4.x release so perhaps this is not an issue on current master (I haven't attempted to reproduce there).

**Comment by gmr** [comment]
``time.sleep`` and blocking is generally a bad thing. I'll add a FAQ to help with this, but you're blocking the IOLoop from running when doing so.

I'd suggest one of two options:

1. Set heartbeat to 0
2. Use a pattern where your long running, blocking processing runs in a thread and loop while that's running between checking if it's done and sleeping using `tornado.gen.sleep`:

```python
import threading
import time

from rejected import consumer
from tornado import gen

__version__ = '1.0.0'


class Consumer(consumer.Consumer):

    @gen.coroutine
    def process(self):
        thread = threading.Thread(target=self.blocking_thing)
        thread.start()
        while thread.is_alive():
            yield gen.sleep(1)
            self.logger.debug('Still waiting on thread')
        self.logger.info('Done')

    def blocking_thing(self):
        self.logger.info('Starting the blocking sleep')
        time.sleep(30)
        self.logger.info('Done blocking sleep')
```

**Comment by gmr** [comment]
Added the example code and config to master.

**Comment by gmr** [comment]
Please let me know if this helps address your issue.

**Comment by code-fabriek** [comment]
@gmr - thanks for the info, much appreciated!

I took your suggestion and moved the blocking function to be called in a separate thread so the IOLoop isn't blocked, and it seems to work great now.  I ended up using adding a `concurrent.futures.ThreadPoolExecutor` to my consumer.  So my solution looks something like:

```python
from rejected import consumer
from tornado import gen

class Consumer(consumer.Consumer):

    executor = ThreadPoolExecutor(4)

    @gen.coroutine
    def process(self):
        yield self.executor.submit(self.blocking_thing)

    def blocking_thing(self):
        self.logger.info('Starting the blocking sleep')
        time.sleep(30)
        self.logger.info('Done blocking sleep')
```

**Comment by gmr** [comment]
I'll crib this for the blocking example code, didn't even think of that, thanks!
