### ISSUE TITLE
Exception log: /var/log/rejected.errors 

### ISSUE THREAD

**Issue by sinhngn** [gmr/rejected#34]
i use python3, but lib still ussing python2

---
rejected -c examples.yaml -p . -o sync

ERROR: Startup of rejected Failed
.Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/helper/unix.py", line 91, in start
    self._daemonize()
  File "/Library/Python/2.7/site-packages/helper/unix.py", line 152, in _daemonize
    if os.getuid() != self.uid:
  File "/Library/Python/2.7/site-packages/helper/unix.py", line 139, in uid
    self._uid = pwd.getpwnam(self.config.daemon.user).pw_uid
KeyError: 'getpwnam(): name not found: rejected'

Exception log: /var/log/rejected.errors

**Comment by gmr** [comment]
Looks like you installed it with python 2.7. Uninstall it and install it with pip3.
